- .gitignore
- src/Domains/Domains.jl
- src/Domains/Ray.jl
- src/Spaces/Laguerre/Laguerre.jl
- test/LaguerreTest.jl
A small change to make the Laguerre code work for general rays.
> Added mapping of points to deal with general Rays

- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- test/UltrasphericalTest.jl
> Ultraspherical conversion error catching

- Project.toml
- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- test/OperatorTest.jl
On master
```julia
julia> v1 = Fun(Chebyshev(), Float64[])
(::Fun{Chebyshev{ChebyshevInterval{Float64}, Float64}, Float64, Vector{Float64}}) (generic function with 1 method)
julia> sp = Ultraspherical(1)
Ultraspherical{Int64, ChebyshevInterval{Float64}, Float64}(1, -1.0..1.0 (Chebyshev))
julia> Multiplication(v1, sp)
ERROR: BoundsError: attempt to access 0-element Vector{Float64} at index [1]
Stacktrace:
[1] getindex
@ ./array.jl:861 [inlined]
[2] SymToeplitzOperator(V::Vector{Float64})
@ ApproxFunBase ~/.julia/packages/ApproxFunBase/fvVRN/src/Operators/banded/ToeplitzOperator.jl:25
[3] Multiplication(f::Fun{Chebyshev{ChebyshevInterval{Float64}, Float64}, Float64, Vector{Float64}}, sp::Ultraspherical{Int64, ChebyshevInterval{Float64}, Float64})
@ ApproxFunOrthogonalPolynomials …
```
> Handle empty coeff vectors in Multiplication for Ultraspherical spaces

- src/Spaces/Hermite/Hermite.jl
The docstring was incorrectly applied to `Fun` instead of the constructor.
> fix `GaussWeight` docstring

- Project.toml
- src/Spaces/Chebyshev/Chebyshev.jl
- test/ChebyshevTest.jl
These are supported by `FastTransforms`, so we may add these here. After this, the following works:
```julia
julia> v = rand(10);
julia> v2 = copy(v);
julia> transform!(Chebyshev(), v);
julia> transform(Chebyshev(), v2) == v
true
```
> Inplace `Chebyshev` transform

- .github/workflows/ci.yml
- Project.toml
- src/Spaces/Jacobi/Jacobi.jl
- test/JacobiTest.jl
Address a common case of the domain being an interval, by recognizing that a constant corresponds to the `n=0` coefficient. After this,
```julia
julia> @inferred Fun(identity, Legendre(-1..1))
Fun(Legendre(-1..1), [0.0, 1.0])
```
> type-stability in Fun(identity, ::Jacobi)

- Project.toml
- src/Spaces/Jacobi/JacobiOperators.jl
- test/JacobiTest.jl
Fixes
```julia
julia> S = Chebyshev(0..1)
Chebyshev(0..1)
julia> union(S, setdomain(Jacobi(S), 1..2))
Jacobi(-0.5,-0.5,0..1)⨄Jacobi(-0.5,-0.5,1..2)
julia> union(Chebyshev(0..1), Legendre(1..2))
Chebyshev(0..1)⨄Legendre(1..2)
```
> union rule for Chebyshev and Jacobi

- Project.toml
- src/Spaces/Ultraspherical/ContinuousSpace.jl
- src/specialfunctions.jl
- test/SpacesTest.jl
After this:
```julia
julia> sc=Fun(sin, ContinuousSpace(PiecewiseSegment([-2,(-π/2),0,π/2,2])));
julia> sc * sc == sc^2
true
```
> Multiplication of `Fun{<:ContinuousSpace}`

- Project.toml
- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- test/UltrasphericalTest.jl
This improves the type inference, as the result becomes a union of concrete types.
Master:
```julia
julia> @code_warntype Conversion(Chebyshev(), Ultraspherical(1))
MethodInstance for Conversion(::Chebyshev{ChebyshevInterval{Float64}, Float64}, ::Ultraspherical{Int64, ChebyshevInterval{Float64}, Float64})
from Conversion(A::Chebyshev, B::Ultraspherical) in ApproxFunOrthogonalPolynomials at /home/jishnu/Dropbox/JuliaPackages/ApproxFunOrthogonalPolynomials.jl/src/Spaces/Ultraspherical/UltrasphericalOperators.jl:120
Arguments
#self#::Type{Conversion}
A::Core.Const(Chebyshev())
B::Ultraspherical{Int64, ChebyshevInterval{Float64}, Float64}
Locals
US::Ultraspherical{Int64, ChebyshevInterval{Float64}, Float64}
d::ChebyshevInterval{Float64} …
```
> Inference in `Chebyshev`/`Ultraspherical` conversion

- Project.toml
- src/Spaces/Jacobi/JacobiOperators.jl
- test/JacobiTest.jl
After this PR, the following works:
```julia
julia> f = Fun(Jacobi(0,0), Float64[1,2,3])
Fun(Legendre(), [1.0, 2.0, 3.0])
julia> Evaluation(1) * f
6.0 on Point(1)
```
> fix jacobi evaluation

- .github/workflows/ci.yml
- Project.toml
- src/Spaces/PolynomialSpace.jl
- test/ChebyshevTest.jl
- test/JacobiTest.jl
- test/UltrasphericalTest.jl
This allows one to obtain
```julia
julia> f = Fun(NormalizedLegendre(0..1))
Fun(NormalizedLegendre(0..1), [0.5, 0.28867513459481287])
julia> f(0.4)
0.4
```
On master, this falls back to using `Chebyshev` as the space. Such a construction should work as long as the conversion between the canonical and the normalized space is defined.
> Identity Fun in normalized Polynomial spaces

- Project.toml
- src/Spaces/Jacobi/JacobiOperators.jl
- src/Spaces/PolynomialSpace.jl
- test/ChebyshevTest.jl
- test/JacobiTest.jl
With this PR, the following works:
```julia
julia> Derivative(NormalizedChebyshev(-1..1))
DerivativeWrapper : NormalizedChebyshev(-1..1) → Ultraspherical(1,-1..1)
⋅  0.7978845608028654   ⋅                   ⋅                   ⋅                  …   ⋅                  ⋅                  ⋅                  ⋅                  ⋅
⋅   ⋅                  1.5957691216057308   ⋅                   ⋅                      ⋅                  ⋅                  ⋅                  ⋅                  ⋅
⋅   ⋅                   ⋅                  2.3936536824085963   ⋅                      ⋅                  ⋅                  ⋅                  ⋅                  ⋅
⋅   ⋅                   ⋅                   ⋅                  3.1915382432114616      ⋅                  ⋅                  ⋅ …
```
> `setdomain` for `NormalizedPolynomialSpace`

- src/Spaces/Jacobi/JacobiOperators.jl
- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- test/JacobiTest.jl
This provides a slight improvement
```julia
julia> A = Chebyshev(); B = Jacobi(1,1);
julia> @btime Conversion($(Ref(A))[], $(Ref(B))[]);
2.444 μs (32 allocations: 1.12 KiB) # master
2.322 μs (31 allocations: 1.09 KiB) # PR
```
> `ConcreteConversion` in `Chebyshev`-`Jacobi`

- Project.toml
- src/Spaces/PolynomialSpace.jl
- test/ChebyshevTest.jl
The following works after this:
```julia
julia> (Derivative() + Fun(NormalizedChebyshev())) * Fun(NormalizedChebyshev())
Fun(Ultraspherical(1), [1.25, 0.0, 0.25])
```
> `conversion_type` for normalized spaces and canonical

- src/Spaces/Jacobi/JacobiOperators.jl
- test/JacobiTest.jl
Following https://en.wikipedia.org/wiki/Jacobi_polynomials#Derivatives, `d/dx(P^(a.b)_n(x))=(..) P^(a+1.b+1)_{n-1}(x)`, so only one band should be populated
On master
```julia
julia> Derivative(Legendre())
ConcreteDerivative : Legendre() → Jacobi(1.0,1.0)
0.0  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   0.0  1.5   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅   0.0  2.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅   0.0  2.5   ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅   0.0  3.0   ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅   0.0  3.5   ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.0  4.0   ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.0  4.5   ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.0  5.0  ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.0  ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ …
```
> Negative lower bandwidth for Jacobi derivative

- Project.toml
- src/Spaces/Spaces.jl
- src/Spaces/Ultraspherical/ContinuousSpace.jl
- test/runtests.jl
Primarily test for unbound parameters
> Use Aqua for project quality test

- Project.toml
- src/bary.jl
- src/specialfunctions.jl
Remove `barysum`, which is exported but undefined.
The compat limit on `ApproxFunBase` is keeping in mind the removal of the exported but undefined symbol `jumplocations` from it. Currently,
```julia
julia> @which jumplocations
ApproxFunOrthogonalPolynomials
```
so the export from `ApproxFunBase` is not having any impact. This will be removed in `ApproxFunBase` v0.6.22, which is technically not a breaking change, as the exported symbol isn't defined.
> Remove barysum

- Project.toml
It's better to release a breaking version for `ApproxFunBase`, as we can't restrict the compat bounds on released versions of `ApproxFunOrthogonalPolynomials`.  In that case we don't need an upper limit for the 0.6 series.
> Update ApproxFunBase compat limit

- Project.toml
- src/Spaces/Hermite/Hermite.jl
On master
```julia
julia> Derivative(Hermite())
ConcreteDerivative : Hermite{Float64}(1.0) → Hermite{Float64}(1.0)
0.0  2.0   ⋅    ⋅    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅   0.0  4.0   ⋅    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅    ⋅   0.0  6.0   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅    ⋅    ⋅   0.0  8.0    ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅    ⋅    ⋅    ⋅   0.0  10.0    ⋅     ⋅     ⋅     ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    0.0  12.0    ⋅     ⋅     ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅     ⋅    0.0  14.0    ⋅     ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅     ⋅     ⋅    0.0  16.0    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅     ⋅     ⋅     ⋅    0.0  18.0  ⋅
⋅    ⋅    ⋅    ⋅    ⋅     ⋅     ⋅     ⋅     ⋅    0.0  ⋱
⋅    ⋅    ⋅    ⋅    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋱
```
This PR
```julia
julia> Derivative(Hermite()) …
```
> lower bandwidth for `Derivative(::Hermite)`

- Project.toml
- src/Spaces/PolynomialSpace.jl
- src/Spaces/Ultraspherical/ContinuousSpace.jl
- test/ChebyshevTest.jl
- test/MultivariateTest.jl
- test/miscAFBase.jl
After this, the following is type-inferred on Julia v1.8:
```julia
julia> @inferred Dirichlet((0..1)^2);
```
> improve inference of Dirichlet

- Project.toml
- src/Spaces/PolynomialSpace.jl
- test/JacobiTest.jl
This is an attempt to get the following to be banded:
```julia
julia> Multiplication(Fun(), NormalizedLegendre())
MultiplicationWrapper : NormalizedLegendre() → NormalizedLegendre()
0.0      0.57735    ⋅         ⋅         ⋅         ⋅         ⋅         ⋅         ⋅         ⋅        ⋅
0.57735  0.0       0.516398   ⋅         ⋅         ⋅         ⋅         ⋅         ⋅         ⋅        ⋅
⋅       0.516398  0.0       0.507093   ⋅         ⋅         ⋅         ⋅         ⋅         ⋅        ⋅
⋅        ⋅        0.507093  0.0       0.503953   ⋅         ⋅         ⋅         ⋅         ⋅        ⋅
⋅        ⋅         ⋅        0.503953  0.0       0.502519   ⋅         ⋅         ⋅         ⋅        ⋅
⋅        ⋅         ⋅         ⋅        0.502519  0.0       0.501745   ⋅         ⋅         ⋅        ⋅
⋅        ⋅ …
```
> Preserve bandwidth in multiplication

- Project.toml
- src/Spaces/Chebyshev/ChebyshevOperators.jl
- test/ChebyshevTest.jl
After this, the following is type-inferred:
```julia
julia> @inferred (r -> Dirichlet(r))(Chebyshev(0..1))
ConcreteDirichlet : Chebyshev(0..1) → 2-element ArraySpace:
ConstantSpace{DomainSets.Point{Int64}, Float64}[ConstantSpace(Point(0)), ConstantSpace(Point(1))]
1.0  -1.0  1.0  -1.0  1.0  -1.0  1.0  -1.0  1.0  -1.0  ⋯
1.0   1.0  1.0   1.0  1.0   1.0  1.0   1.0  1.0   1.0  ⋯
```
> Aggressive constprop in Dirichlet

- src/Spaces/Laguerre/Laguerre.jl
This PR makes the derivative of `Laguerre` polynomials on the real axis real.
After this:
```julia
julia> Derivative(Laguerre())
DerivativeWrapper : Laguerre{Int64, Ray{false, Float64}}(0, 【0.0,∞❫) → Laguerre{Int64, Ray{false, Float64}}(1, 【0.0,∞❫)
0.0  -1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅    0.0  -1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅     ⋅    0.0  -1.0    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅     ⋅     ⋅    0.0  -1.0    ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅     ⋅     ⋅     ⋅    0.0  -1.0    ⋅     ⋅     ⋅     ⋅   ⋅
⋅     ⋅     ⋅     ⋅     ⋅    0.0  -1.0    ⋅     ⋅     ⋅   ⋅
⋅     ⋅     ⋅     ⋅     ⋅     ⋅    0.0  -1.0    ⋅     ⋅   ⋅
⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    0.0  -1.0    ⋅   ⋅
⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅     ⋅    0.0  -1.0  ⋅
⋅     ⋅ …
```
> Laguerre derivative on real line

- test/runtests.jl
- test/testutils.jl
This makes tests simpler, as we may include `test/testutils.jl` before including a test file.
> Split test macro to separate file

- Project.toml
- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- test/ChebyshevTest.jl
- test/UltrasphericalTest.jl
- test/miscAFBase.jl
After this, the following is fully type-inferred:
```julia
julia> @inferred (() -> Fun() * Derivative(Chebyshev()))()
TimesOperator : Chebyshev() → Ultraspherical(1)
0.0  0.0  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   0.5  0.0  1.5   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅   1.0  0.0  2.0   ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅   1.5  0.0  2.5   ⋅    ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅   2.0  0.0  3.0   ⋅    ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅   2.5  0.0  3.5   ⋅    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅   3.0  0.0  4.0   ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   3.5  0.0  4.5  ⋅
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   4.0  0.0  ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   4.5  ⋱
⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋱
```
> Constant propagation in `Multiplication(f, ::Ultraspherical)`

- Project.toml
- src/Spaces/Chebyshev/ChebyshevOperators.jl
- src/Spaces/Hermite/Hermite.jl
- src/Spaces/Jacobi/JacobiOperators.jl
- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
This would help with constant propagation in certain cases, using static integers as orders. Currently, `StaticInt`s are not `Integer`s, although https://github.com/SciML/Static.jl/pull/92 would mean that this change in unnecessary, in which case this may be reverted.
```julia
julia> @code_typed rangespace(Derivative(Chebyshev(), 1))
CodeInfo(
1 ─ %1 = Base.getfield(D, :order)::Int64
│   %2 = (%1 === 0)::Bool
│   %3 = Base.not_int(%2)::Bool
└──      goto #3 if not %3
2 ─ %5 = %new(Ultraspherical{Int64, ChebyshevInterval{Float64}, Float64}, %1, $(QuoteNode(-1.0..1.0 (Chebyshev))))::Ultraspherical{Int64, ChebyshevInterval{Float64}, Float64}
└──      goto #4
3 ─ %7 = %new(Core.AssertionError, "m ≠ 0")::AssertionError
│        Base.throw(%7)::Union{}
└──      unreachable
4 ─      goto #5
5 ─ …
```
> Accept `Number` orders in calculus operators

- test/SpacesTest.jl
This test fails intermittently, and I'm not being able to replicate the error locally. I'm disabling this for now while I look into it
> Skip `jumplocations` test for sign sum

- Project.toml
- src/Spaces/IntervalSpace.jl
- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- test/ChebyshevTest.jl
- test/UltrasphericalTest.jl
This harms type-inferrence, as `Space(d::Interval)` isn't concretely inferred.
> revert moving integral over domain

- Project.toml
- src/Domains/Ray.jl
- test/LaguerreTest.jl
After this, the following is type-inferred:
```julia
julia> @inferred Ray(0..Inf)
【0.0,∞❫
```
> improve inference in Ray

- Project.toml
- src/Spaces/Jacobi/Jacobi.jl
- src/Spaces/Jacobi/JacobiOperators.jl
- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- test/JacobiTest.jl
- test/UltrasphericalTest.jl
- test/showtest.jl
Using integer orders makes comparisons with integers easier, e.g. `n + 0.5` is statically known to not be an integer if `n` is an integer.
On master
```julia
julia> @inferred ApproxFunBase.maxspace(Jacobi(1,1), Jacobi(2,2))
ERROR: return type Jacobi{ChebyshevInterval{Float64}, Float64} does not match inferred return type Any
Stacktrace:
[1] error(s::String)
@ Base ./error.jl:35
[2] top-level scope
@ REPL[5]:1
```
After this PR, this is fully type-inferred.
```julia
julia> @inferred ApproxFunBase.maxspace(Jacobi(1,1), Jacobi(2,2))
Jacobi(2,2)
```
> Add type parameter to Jacobi

- Project.toml
- src/Spaces/Jacobi/JacobiOperators.jl
- test/JacobiTest.jl
After this, the following is inferred:
```julia
julia> @inferred Derivative(Legendre())
ConcreteDerivative : Legendre() → Jacobi(1,1)
⋅  1.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   ⋅   1.5   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   ⋅    ⋅   2.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   ⋅    ⋅    ⋅   2.5   ⋅    ⋅    ⋅    ⋅    ⋅   ⋅
⋅   ⋅    ⋅    ⋅    ⋅   3.0   ⋅    ⋅    ⋅    ⋅   ⋅
⋅   ⋅    ⋅    ⋅    ⋅    ⋅   3.5   ⋅    ⋅    ⋅   ⋅
⋅   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   4.0   ⋅    ⋅   ⋅
⋅   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   4.5   ⋅   ⋅
⋅   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   5.0  ⋅
⋅   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋱
⋅   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   ⋱
```
> constprop in jacobi derivative

- src/Spaces/Jacobi/Jacobi.jl
- test/JacobiTest.jl
Defining `Legendre` using `StaticInt` leads to slowdowns. I'm still investigating the source of these slowdowns, but as of now it's better to revert the change. Static integers are still an opt-in, and can be used to improve inference.
> Don't define Legendre using StaticInt

- Project.toml
- src/Spaces/Chebyshev/Chebyshev.jl
- src/Spaces/Hermite/Hermite.jl
- src/Spaces/Jacobi/Jacobi.jl
- src/Spaces/Jacobi/JacobiOperators.jl
- src/Spaces/Laguerre/Laguerre.jl
- src/Spaces/Ultraspherical/Ultraspherical.jl
- test/ChebyshevTest.jl
- test/JacobiTest.jl
- test/UltrasphericalTest.jl
After this,
```julia
julia> NormalizedChebyshev() isa NormalizedChebyshev
true
```
This works for most cases, except `NormalizedLegendre`, which isn't its own type.
```julia
julia> NormalizedLegendre() isa NormalizedJacobi
true
```
> Define Normalized type aliases

- Project.toml
- src/Spaces/PolynomialSpace.jl
- test/JacobiTest.jl
After this, the following works:
```julia
julia> ApproxFunBase.hasconversion(Chebyshev()*Legendre(), Chebyshev()*NormalizedLegendre())
true
```
On master
```julia
julia> f = Fun((x,y)->x^10*y^4 + x^2*y^3, Chebyshev()*Legendre());
```
TTFX
```julia
julia> @time Fun(f, Chebyshev()*NormalizedLegendre());
12.396606 seconds (41.16 M allocations: 2.226 GiB, 6.72% gc time, 99.99% compilation time)
```
Benchmark
```julia
julia> @btime Fun($f, Chebyshev()*NormalizedLegendre());
287.812 μs (416 allocations: 66.70 KiB)
```
This PR
TTFX
```julia
julia> @time Fun(f, Chebyshev()*NormalizedLegendre());
10.915021 seconds (38.30 M allocations: 2.089 GiB, 6.96% gc time, 99.99% compilation time)
```
Benchmark
```julia
julia> @btime Fun($f, Chebyshev()*NormalizedLegendre());
66.401 μs (1386 allocations: …
```
> hasconversion for tensorspace

- Project.toml
- src/Spaces/Ultraspherical/ContinuousSpace.jl
This used to error with `julia --project --depwarn=error`
> Fix deprecated Vararg syntax

- Project.toml
- src/ApproxFunOrthogonalPolynomials.jl
- src/Spaces/Chebyshev/Chebyshev.jl
- src/Spaces/PolynomialSpace.jl
On master
```julia
julia> @btime Fun(x -> x^20, Chebyshev());
107.806 μs (218 allocations: 19.08 KiB)
```
This PR
```julia
julia> @btime Fun(x -> x^20, Chebyshev());
33.232 μs (118 allocations: 8.50 KiB)
```
The improvement comes from allocating fewer arrays, and carrying out transforms in-place.
> `supportsinplacetransform` for float-domain Chebyshev

- src/Spaces/Jacobi/Jacobi.jl
- src/Spaces/Jacobi/JacobiOperators.jl
- src/Spaces/Ultraspherical/Ultraspherical.jl
- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- test/UltrasphericalTest.jl
After this, the following become type-inferred:
```julia
julia> @inferred Conversion(Ultraspherical(static(1)), Ultraspherical(static(4)));
julia> @inferred (() -> Conversion(Ultraspherical(1), Ultraspherical(static(4))))();
```
Also, generalizes Ultraspherical transforms, so that the following work now:
```julia
julia> Fun(x->x^2, NormalizedUltraspherical(3.5))
Fun(NormalizedUltraspherical(3.5), [0.106243, 0.0, 0.128133])
julia> Fun(x->x^2, NormalizedJacobi(3,3))
Fun(NormalizedJacobi(3,3), [0.106243, 0.0, 0.128133])
julia> Fun(x->x^2, NormalizedUltraspherical(3.5)) ≈ Fun(x->x^2)
true
```
> static integer orders in Ultraspherical spaces

- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
This improves performance, as the type of the result is easier to infer.
> ConcreteConversions in ultraspherical conversion

- src/Spaces/Jacobi/JacobiOperators.jl
- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- test/UltrasphericalTest.jl
After this, `Conversion(Jacobi(1,1), Jacobi(2,2))` is inferred as a small union of concretely inferred types.
> simplify jacobi conversion

- src/Spaces/Jacobi/JacobiOperators.jl
- src/Spaces/PolynomialSpace.jl
- test/JacobiTest.jl
After this, the following is type-inferred:
```julia
julia> @inferred Multiplication(Fun(Legendre()), NormalizedLegendre())
MultiplicationWrapper : NormalizedLegendre() → NormalizedLegendre()
0.0      0.57735    ⋅         ⋅         ⋅         ⋅         ⋅         ⋅         ⋅         ⋅        ⋅
0.57735  0.0       0.516398   ⋅         ⋅         ⋅         ⋅         ⋅         ⋅         ⋅        ⋅
⋅       0.516398  0.0       0.507093   ⋅         ⋅         ⋅         ⋅         ⋅         ⋅        ⋅
⋅        ⋅        0.507093  0.0       0.503953   ⋅         ⋅         ⋅         ⋅         ⋅        ⋅
⋅        ⋅         ⋅        0.503953  0.0       0.502519   ⋅         ⋅         ⋅         ⋅        ⋅
⋅        ⋅         ⋅         ⋅        0.502519  0.0       0.501745   ⋅         ⋅         ⋅        ⋅
⋅ …
```
> Inference in normalized space multiplication

- src/Spaces/PolynomialSpace.jl
- test/JacobiTest.jl
This makes the following type-stable:
```julia
julia> @inferred Derivative(NormalizedLegendre(), 2)
DerivativeWrapper : NormalizedLegendre() → Jacobi(2,2)
⋅  ⋅  4.74342   ⋅         ⋅        ⋅        ⋅        ⋅       ⋅        ⋅      ⋅
⋅  ⋅   ⋅       9.35414    ⋅        ⋅        ⋅        ⋅       ⋅        ⋅      ⋅
⋅  ⋅   ⋅        ⋅       15.9099    ⋅        ⋅        ⋅       ⋅        ⋅      ⋅
⋅  ⋅   ⋅        ⋅         ⋅      24.6247    ⋅        ⋅       ⋅        ⋅      ⋅
⋅  ⋅   ⋅        ⋅         ⋅        ⋅      35.6931    ⋅       ⋅        ⋅      ⋅
⋅  ⋅   ⋅        ⋅         ⋅        ⋅        ⋅      49.295    ⋅        ⋅      ⋅
⋅  ⋅   ⋅        ⋅         ⋅        ⋅        ⋅        ⋅     65.5982    ⋅      ⋅
⋅  ⋅   ⋅        ⋅         ⋅        ⋅        ⋅        ⋅       ⋅      84.7607  ⋅
⋅  ⋅   ⋅ …
```
> Derivative in normalized polynomial spaces

- Project.toml
- src/Spaces/Chebyshev/ChebyshevOperators.jl
- src/Spaces/PolynomialSpace.jl
- src/Spaces/Ultraspherical/ContinuousSpace.jl
- src/fastops.jl
Purely stylistic change to replace `Tuple{UnitRange{Int},UnitRange{Int}}` by `NTuple{2,UnitRange{Int}}`
> use NTuple{2,UnitRange{Int}}

- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- test/UltrasphericalTest.jl
Fix the case where the order of the ultraspherical space matches the order of the integral, and is greater than 1.
> Fix ultraspherical Integral indexing

- src/ApproxFunOrthogonalPolynomials.jl
- src/Spaces/Jacobi/Jacobi.jl
- src/Spaces/Laguerre/Laguerre.jl
- src/Spaces/Ultraspherical/Ultraspherical.jl
- test/JacobiTest.jl
We assume that integer orders are deliberately chosen to be so, and use an exact comparison if one of the two spaces has an integer order. If both spaces have non-integer orders, this falls back to an approximate comparison
This also makes `spacescompatible` consistent across spaces.
> Use `==` for Integer in spacescompatible

- Project.toml
- src/Spaces/Jacobi/Jacobi.jl
- test/JacobiTest.jl
On master
```julia
julia> Conversion(Jacobi(-0.5, -0.5), NormalizedJacobi(-0.5, -0.5))
ConcreteConversion : Jacobi(-0.5,-0.5) → NormalizedJacobi(-0.5,-0.5)
NaN    ⋅         ⋅         ⋅         ⋅         ⋅         ⋅        ⋅         ⋅         ⋅        ⋅
⋅  0.626657   ⋅         ⋅         ⋅         ⋅         ⋅        ⋅         ⋅         ⋅        ⋅
⋅   ⋅        0.469993   ⋅         ⋅         ⋅         ⋅        ⋅         ⋅         ⋅        ⋅
⋅   ⋅         ⋅        0.391661   ⋅         ⋅         ⋅        ⋅         ⋅         ⋅        ⋅
⋅   ⋅         ⋅         ⋅        0.342703   ⋅         ⋅        ⋅         ⋅         ⋅        ⋅
⋅   ⋅         ⋅         ⋅         ⋅        0.308433   ⋅        ⋅         ⋅         ⋅        ⋅
⋅   ⋅         ⋅         ⋅         ⋅         ⋅        0.28273   ⋅         ⋅ …
```
> Normalized jacobi conversion for alpha=beta=-0.5

- Project.toml
- src/ApproxFunOrthogonalPolynomials.jl
- src/Spaces/Chebyshev/ChebyshevOperators.jl
- src/Spaces/Jacobi/JacobiOperators.jl
- src/Spaces/PolynomialSpace.jl
- src/Spaces/Ultraspherical/DirichletSpace.jl
- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- test/ChebyshevTest.jl
- test/JacobiTest.jl
- test/UltrasphericalTest.jl
After this,
```julia
julia> bvp(Chebyshev())
2-element Vector{ApproxFunBase.ConcreteEvaluation{Chebyshev{ChebyshevInterval{Float64}, Float64}, ApproxFunBase.Boundary, Int64, Float64}}:
ConcreteEvaluation : Chebyshev() → ConstantSpace(Point(-1.0))
ConcreteEvaluation : Chebyshev() → ConstantSpace(Point(1.0))
```
where the `eltype` is concrete.
> Don't dispatch on leftendpoint/rightendpoint in Evaluation

- Project.toml
- src/ApproxFunOrthogonalPolynomials.jl
- src/Spaces/PolynomialSpace.jl
- test/ChebyshevTest.jl
This provides a uniform way to construct normalized spaces over intervals/segments or piecewise domains:
```julia
julia> d = Segment(-1..0)∪Segment(0..1)
the segment [-1.0,0.0] ∪ the segment [0.0,1.0]
julia> S = PiecewiseSpace(Chebyshev.(components(d)))
Chebyshev(the segment [-1.0,0.0]) ⨄ Chebyshev(the segment [0.0,1.0])
julia> normalized(S)
NormalizedChebyshev(the segment [-1.0,0.0]) ⨄ NormalizedChebyshev(the segment [0.0,1.0])
julia> S = Chebyshev(0..1)
Chebyshev(0..1)
julia> normalized(S)
NormalizedChebyshev(0..1)
```
> Extend `normalizedspace` for `PolynomialSpace`

- src/Spaces/PolynomialSpace.jl
- test/JacobiTest.jl
After this,
```julia
julia> conversion_type(NormalizedLegendre(), Jacobi(1,1))
NormalizedLegendre()
julia> conversion_type(NormalizedJacobi(2,2), Jacobi(1,1))
Jacobi(1,1)
```
> Fix `conversion_type` for `NormalizedPolynomialSpace`

- Project.toml
- src/ApproxFunOrthogonalPolynomials.jl
- src/Spaces/Jacobi/Jacobi.jl
- src/symeigen.jl
- test/EigTest.jl
- test/JacobiTest.jl
This provides a convenient function for the Aurentz-Slevinsky eigenvalue problem symmetrization.
After this
```julia
L = -Derivative(Legendre(0..1))^2
B = Dirichlet()
S = ApproxFun.SymmetricEigensystem(L, B);
λ = eigvals(S,20); # return 20 eigenvalues
```
> Add convenience functions for symmetric eigen BandedMatrices

- Project.toml
- src/Spaces/PolynomialSpace.jl
- test/ChebyshevTest.jl
- test/ClenshawTest.jl
- test/ComplexTest.jl
- test/EigTest.jl
- test/HermiteTest.jl
- test/JacobiTest.jl
- test/LaguerreTest.jl
- test/MultivariateTest.jl
- test/ODETest.jl
- test/OperatorTest.jl
- test/PDETest.jl
- test/SpacesTest.jl
- test/UltrasphericalTest.jl
- test/VectorTest.jl
- test/broadcastingtest.jl
- test/showtest.jl
Also, remove the `Derivative` specialization for `NormalizedPolynomialSpace`s, as this isn't necessary on recent versions of `ApproxFunBase`
> Modules in tests

- Project.toml
- src/Spaces/Jacobi/JacobiOperators.jl
- src/Spaces/PolynomialSpace.jl
- test/JacobiTest.jl
After this,
```julia
julia> C = Conversion(Ultraspherical(0.5), Legendre());
julia> @btime $C[1:100, 1:100];
169.329 ns (2 allocations: 944 bytes) # PR
821.360 ns (6 allocations: 4.42 KiB) # master
```
This also fixes
```julia
julia> Conversion(NormalizedUltraspherical(1.5), NormalizedJacobi(1,1))
ConversionWrapper : NormalizedUltraspherical(1.5) → NormalizedJacobi(1,1)
1.0000000000000002   ⋅                  …   ⋅                   ⋅   ⋅
⋅                  1.0000000000000002      ⋅                   ⋅   ⋅
⋅                   ⋅                      ⋅                   ⋅   ⋅
⋅                   ⋅                      ⋅                   ⋅   ⋅
⋅                   ⋅                      ⋅                   ⋅   ⋅
⋅                   ⋅                  …   ⋅                   ⋅   ⋅
⋅ …
```
> Faster indexing for `Ultraspherical(0.5)` ⟷ `Legendre`

- test/UltrasphericalTest.jl
These tests require a high compilation time, but they aren't necessary technically, as the 3D transforms are tested for Chebyshev, and are essentially a sequence of 2D transforms.
> remove ultraspherical 3d inplace transform tests

- Project.toml
- src/Spaces/Chebyshev/ChebyshevOperators.jl
On master
```julia
julia> D = ldirichlet(Chebyshev());
julia> @btime $D[1:100];
1.416 μs (1 allocation: 896 bytes)
```
After this
```julia
julia> @btime $D[1:100];
136.291 ns (1 allocation: 896 bytes)
```
> Speed-up Chebyshev ldirichlet indexing

- src/Spaces/Ultraspherical/DirichletSpace.jl
On master
```julia
julia> S = ChebyshevDirichlet{0,1}()
julia> @btime Evaluation($S, leftendpoint)[1:100];
940.091 ns (1 allocation: 896 bytes)
```
This PR
```julia
julia> @btime Evaluation($S, leftendpoint)[1:100];
76.757 ns (1 allocation: 896 bytes)
```
> Speed up ChebyshevDirichlet leftendpoint indexing

- Project.toml
- src/Spaces/PolynomialSpace.jl
- test/UltrasphericalTest.jl
This was hitting the fallback method previously, which was slow.
On master
```julia
julia> E = Evaluation(NormalizedUltraspherical(1), 0.5);
julia> @btime $E[1,1];
2.391 μs (23 allocations: 704 bytes)
```
This PR
```julia
julia> @btime $E[1,1];
183.369 ns (2 allocations: 128 bytes)
```
> Faster evaluation in normalized spaces

- test/ChebyshevTest.jl
It's better to test for approximate equality to avoid breakages from changes to floating-point return values. This was one of the failing tests in #273
> Make points test approximate

- Project.toml
- src/Spaces/Chebyshev/Chebyshev.jl
- src/Spaces/Ultraspherical/Ultraspherical.jl
- test/ChebyshevTest.jl
- test/UltrasphericalTest.jl
After this, the following is consistent (the same types are returned):
```julia
julia> f = Fun(Chebyshev(), [1,2])
Fun(Chebyshev(), [1, 2])
julia> first(f)
-1.0
julia> f(-1)
-1.0
```
> first/last return floats for `Int` coefficients

- src/Spaces/Chebyshev/Chebyshev.jl
On master
```julia
julia> f = Fun();
julia> @btime integrate($f)
108.817 ns (3 allocations: 240 bytes)
Fun(Chebyshev(), [0.0, 0.0, 0.25])
```
This PR
```julia
julia> @btime integrate($f)
73.764 ns (2 allocations: 160 bytes)
Fun(Chebyshev(), [0.0, 0.0, 0.25])
```
> Slightly reduce allocations in Chebyshev Fun integrate

- Project.toml
- src/Spaces/Chebyshev/Chebyshev.jl
- src/ultraspherical.jl
- test/ChebyshevTest.jl
On master
```julia
julia> f = Fun(x->x^4, Chebyshev());
julia> @btime $f';
113.291 ns (3 allocations: 288 bytes)
```
This PR
```julia
julia> @btime $f';
55.667 ns (1 allocation: 96 bytes)
```
> reduce allocations in Chebyshev deriv

- Project.toml
- src/ApproxFunOrthogonalPolynomials.jl
- src/Spaces/IntervalSpace.jl
This removes the explicit dependency on Statistics, and these may differ after https://github.com/JuliaApproximation/ApproxFunBase.jl/pull/506
> Use ApproxFunBase.mean instead of Statistics

- Project.toml
- src/ApproxFunOrthogonalPolynomials.jl
- src/Spaces/Jacobi/JacobiOperators.jl
- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- test/JacobiTest.jl
- test/UltrasphericalTest.jl
After this,
```julia
julia> C = Conversion(Chebyshev(), Ultraspherical(2));
julia> using LinearAlgebra
julia> @code_typed isdiag(C) # compile-time constant
CodeInfo(
1 ─     return false
) => Bool
```
> Specialize isdiag for certain `ConversionWrapper`s

- Project.toml
- src/Spaces/PolynomialSpace.jl
- test/UltrasphericalTest.jl
After this, the following is type-stable:
```julia
julia> @inferred Fun(Chebyshev()) + Fun(Ultraspherical(1))
Fun(Chebyshev(), [0.0, 2.0])
```
> Type-stability in polynomial space union

- Project.toml
- ext/ApproxFunOrthogonalPolynomialsPolynomialsExt.jl
- src/ApproxFunOrthogonalPolynomials.jl
- test/ChebyshevTest.jl
On master
```julia
julia> C = ChebyshevT([1,2,3])
ChebyshevT(1⋅T_0(x) + 2⋅T_1(x) + 3⋅T_2(x))
julia> @btime Fun($C, Chebyshev())
14.825 μs (8 allocations: 544 bytes)
Fun(Chebyshev(), [1.0, 2.0, 3.0])
```
This PR
```julia
julia> @btime Fun($C, Chebyshev())
53.640 ns (1 allocation: 80 bytes)
Fun(Chebyshev(), [1.0, 2.0, 3.0])
```
> Conversions from `Polynomials.ChebyshevT`

- Project.toml
- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- test/UltrasphericalTest.jl
This banded conversion shouldn't exist, and it appears to be a mistake.
> Disallow banded Ultraspherical conversion from n+1 to n

- Project.toml
- test/SpacesTest.jl
Tests the implementation of `norm()` and indirectly `integrate()` for ConstantSpace functionals in ApproxFunBase which was added in https://github.com/JuliaApproximation/ApproxFunBase.jl/pull/595.
> Add ConstantSpace test for norm/integrate

- test/ChebyshevTest.jl
Until https://github.com/JuliaLang/julia/issues/50965 is resolved, this test needs to be disabled on Julia v1.10+
> Disable eltype inference test on v1.10+

- Project.toml
- test/ChebyshevTest.jl
Also removed some duplicate tests
> Test for inference using BigFloat interval in Chebyshev

- test/MiscAFBTest.jl
Rely less on `ApproxFunBase` internals
> Update onehotvector tests

- Project.toml
- src/Spaces/PolynomialSpace.jl
- test/ChebyshevTest.jl
On master
```julia
julia> f = NormalizedChebyshev()(3);
julia> @btime $f(0.1);
272.601 ns (2 allocations: 192 bytes)
```
This PR
```julia
julia> @btime $f(0.1);
36.979 ns (0 allocations: 0 bytes)
```
> Faster evaluate in NormalizedPolynomialSpace for OneElement coeffs

- test/VectorTest.jl
Since the domain of the function is a point, it should be evaluated at that point.
> Fix eval point in Floquet dirichlet test

- src/Spaces/Chebyshev/ChebyshevOperators.jl
This makes the method definitions easier to read and extend.
> Fewer type parameters in chebyshev operator methods

- src/Spaces/Chebyshev/Chebyshev.jl
- src/Spaces/Chebyshev/ChebyshevOperators.jl
- src/Spaces/Jacobi/JacobiOperators.jl
- src/Spaces/PolynomialSpace.jl
- src/Spaces/Ultraspherical/UltrasphericalOperators.jl
- src/fastops.jl
- test/ChebyshevTest.jl
- test/JacobiTest.jl
- test/UltrasphericalTest.jl
In cases where the `canonicalspace` supports a concrete operator, the corresponding operator in the normalized space may also be concrete, which will avoid type-inference issues with `TimesOperator` and be much faster overall. E.g., after this,
```julia
julia> Derivative(NormalizedChebyshev(), 2)
ConcreteDerivative : NormalizedChebyshev() → Ultraspherical(2)
⋅    ⋅   3.19154   ⋅        ⋅        ⋅        ⋅         ⋅        ⋅        ⋅      ⋅
⋅    ⋅    ⋅       4.78731   ⋅        ⋅        ⋅         ⋅        ⋅        ⋅      ⋅
⋅    ⋅    ⋅        ⋅       6.38308   ⋅        ⋅         ⋅        ⋅        ⋅      ⋅
⋅    ⋅    ⋅        ⋅        ⋅       7.97885   ⋅         ⋅        ⋅        ⋅      ⋅
⋅    ⋅    ⋅        ⋅        ⋅        ⋅       9.57461    ⋅        ⋅        ⋅      ⋅
⋅    ⋅    ⋅        ⋅ …
```
> Concrete operators in normalized spaces

- src/Spaces/Jacobi/JacobiOperators.jl
- src/Spaces/PolynomialSpace.jl
- test/ChebyshevTest.jl
- test/JacobiTest.jl
- test/MiscAFBTest.jl
- test/UltrasphericalTest.jl
After this,
```julia
julia> g = Derivative() * Chebyshev()(3)
Fun(Ultraspherical(1), [0.0, 0.0, 3.0])
julia> coefficients(g)
3-element FillArrays.OneElement{Float64, 1, Tuple{Int64}, Tuple{Base.OneTo{Int64}}}:
⋅ 
⋅ 
3.0
```
> Concrete derivatives may preserve OneElement coefficients

- src/Spaces/Jacobi/JacobiOperators.jl
- test/ChebyshevTest.jl
- test/JacobiTest.jl
- test/MiscAFBTest.jl
With this, higher-order derivatives in a Jacobi space become concrete instead of being wrappers:
```julia
julia> Derivative(Legendre(), 2)
ConcreteDerivative : Legendre() → Jacobi(2,2)
⋅    ⋅   3.0   ⋅    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅    ⋅    ⋅   5.0   ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅    ⋅    ⋅    ⋅   7.5    ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅   10.5    ⋅     ⋅     ⋅     ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅     ⋅   14.0    ⋅     ⋅     ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅     ⋅     ⋅   18.0    ⋅     ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅     ⋅     ⋅     ⋅   22.5    ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅     ⋅     ⋅     ⋅     ⋅   27.5  ⋅
⋅    ⋅    ⋅    ⋅    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋱
⋅    ⋅    ⋅    ⋅    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅   ⋅
⋅    ⋅    ⋅    ⋅    ⋅     ⋅     ⋅     ⋅     ⋅     ⋅ …
```
> Concrete derivative in Jacobi space

- src/fastops.jl
- test/ChebyshevTest.jl
- test/UltrasphericalTest.jl
With this, the fast method is used to construct a `BandedMatrix` when indexing into a `Derivative` in an `Ultraspherical` space:
```julia
julia> @btime Derivative(Ultraspherical(1))[1:100, 1:100];
188.008 ns (1 allocation: 896 bytes)
```
> Fix method signature in BandedMatrix for Ultraspherical derivative

- .github/workflows/ci.yml
The test failures arise from `FastTransforms.jl` being broken on `macOS-latest`, and we may re-enable these tests when the breakages are fixed.
> Disable `macOS-latest` tests

- Project.toml
- src/ApproxFunOrthogonalPolynomials.jl
A method is being added to the constructor, so this needs to be imported explicitly.
> Import `BlockBandedMatrix` explicitly
