src/roots.jl

the dims keyword in now required for cat

---

src/Spaces/Jacobi/jacobitransform.jl
test/JacobiTest.jl

After this, the following works:
```julia
julia> v = rand(10); v2 = copy(v);
julia> transform!(Legendre(), v);
julia> transform(Legendre(), v2) == v
true
julia> itransform!(Legendre(), v);
julia> v ≈ v2
true
```

Inplace jacobi/Legendre transforms

---

src/Spaces/Jacobi/JacobiOperators.jl
test/JacobiTest.jl

After this PR
```julia
julia> f1 = Fun(x->x, Chebyshev(0..1))
Fun(Chebyshev(0..1), [0.5, 0.5])
julia> f2 = Fun(x->x, Jacobi(-0.5, -0.5, 0..1))
Fun(Jacobi(-0.5,-0.5,0..1), [0.5, 1.0000000000000002])
julia> f1 + f2
Fun(Chebyshev(0..1), [1.0, 1.0])
```

coerce compatible jacobi to chebyshev/ultraspherical

---

Project.toml

Version bump to v0.5.1

---

.github/workflows/CompatHelper.yml

Copied from https://github.com/JuliaRegistries/CompatHelper.jl/blob/master/.github/workflows/CompatHelper.yml

Update compathelper script

---

.github/workflows/downstream.yml

Similar to https://github.com/JuliaApproximation/ApproxFunBase.jl/pull/199

Include downstream in computing coverage

---

Project.toml
src/Spaces/Ultraspherical/Ultraspherical.jl
test/UltrasphericalTest.jl

After this, in-place ultraspherical transforms work:
```julia
julia> v = rand(4);
julia> transform(Ultraspherical(0.5), v)
4-element Vector{Float64}:
0.6565901521249496
0.23852556430139518
-0.13876518587384823
0.18035187772498457
julia> transform!(Ultraspherical(0.5), v);
julia> v
4-element Vector{Float64}:
0.6565901521249496
0.23852556430139518
-0.13876518587384823
0.18035187772498457
```

Inplace ultraspherical transform

---

src/Spaces/Hermite/Hermite.jl

Fix JuliaApproximation/ApproxFun.jl#826

Fix typo, Hemite -> Hermite

---

test/MultivariateTest.jl

Tests for https://github.com/JuliaApproximation/ApproxFunBase.jl/pull/225

tests for lowrankfun inference

---

test/JacobiTest.jl
test/UltrasphericalTest.jl

Tests for https://github.com/JuliaApproximation/ApproxFunBase.jl/pull/232

tests for 2d tensor transforms

---

Project.toml
src/Spaces/PolynomialSpace.jl
test/ChebyshevTest.jl
test/JacobiTest.jl
test/runtests.jl

On master
```julia
julia> 1 + Fun(NormalizedChebyshev())
Fun(ConstantSpace(-1.0..1.0 (Chebyshev))⊕NormalizedChebyshev(), [1.0, 0.0, 1.2533141373155001])
```
After this,
```julia
julia> 1 + Fun(NormalizedChebyshev())
Fun(NormalizedChebyshev(), [1.7724538509055159, 1.2533141373155001])
```

Normalized polynomial spaces contain constant

---

.github/workflows/ci.yml

Use v3 for both to use node.jl 16 jobs

Update cache and codecov actions

---

Project.toml
test/MultivariateTest.jl

Adding multivariate tests, especially for dimensions > 2.

Add multivariate tests

---

Project.toml
src/Spaces/Jacobi/Jacobi.jl
src/Spaces/Ultraspherical/Ultraspherical.jl
test/JacobiTest.jl

After this,
```julia
julia> NormalizedJacobi(NormalizedUltraspherical(1))
NormalizedJacobi(0.5,0.5)
julia> NormalizedUltraspherical(NormalizedJacobi(1.5, 1.5))
NormalizedUltraspherical(2.0)
```

Conversion between normalized `Ultraspherical` and `Jacobi`

---

Project.toml
src/Spaces/PolynomialSpace.jl
test/JacobiTest.jl

After this, the following is type-inferred:
```julia
julia> @inferred Multiplication(Fun(Legendre()), NormalizedLegendre());
```

Domainspace in normalized space multiplication

---

src/Spaces/Jacobi/JacobiOperators.jl

These branches are skipped for integer orders

Chebyshev check in Jacobi conversion

---

src/Spaces/Ultraspherical/UltrasphericalOperators.jl

This makes type-inference easier

simplify chebyshev/ultraspherical conversions

---

test/testutils.jl

Tests being deterministic will make reproducing failures easier

remove rand in test_transform

---

test/miscAFBase.jl

Also, remove some duplicate inplace transform tests

Test for type-inference in `TimesOperator`

---

Project.toml
src/ApproxFunOrthogonalPolynomials.jl
src/symeigen.jl
test/EigTest.jl

This lets one compute the eigenfunctions as well.
```julia
julia> S = -Derivative(Legendre(), 2);
julia> B = Dirichlet();
julia> Seig = SymmetricEigensystem(S, B);
julia> λ, f = eigs(Seig, 100, tolerance=1e-8);
```

`eigs` for EigenSystem

---

src/Spaces/CurveSpace.jl
src/Spaces/Ultraspherical/DirichletSpace.jl
test/SpacesTest.jl

Fixes
```julia
julia> Fun(Bernstein{1}())
Fun(Bernstein{1, ChebyshevInterval{Float64}, Float64}(-1.0..1.0 (Chebyshev)), [-1.0, 1.0])
```

Fix Bernstein Fun

---

Project.toml
ext/ApproxFunOrthogonalPolynomialsStaticExt.jl
src/ApproxFunOrthogonalPolynomials.jl
src/Spaces/Spaces.jl
src/Spaces/Ultraspherical/Ultraspherical.jl
src/Spaces/Ultraspherical/UltrasphericalOperators.jl
src/fastops.jl
src/show.jl
test/UltrasphericalTest.jl
test/showtest.jl

Since this is an opt-in module, we don't need to load this unconditionally.

Move Static to an extension

---

Project.toml
src/Spaces/PolynomialSpace.jl
test/ChebyshevTest.jl
test/MultivariateTest.jl

After this,
```julia
julia> @inferred Fun(Chebyshev(), BigInt[1])(1)
1.0
julia> @inferred Fun(Chebyshev(), [1])(Dual(1,1))
1.0 + 0.0ɛ
```

Improve type-inference in evaluate

---

src/specialfunctions.jl
test/MiscAFBTest.jl

The method is defined in `ApproxFunSingularities`

Remove log

---

test/SpacesTest.jl

Test for https://github.com/JuliaApproximation/ApproxFunBase.jl/pull/560

Test for cumsum(sign(x))

---

Project.toml

Bump version to v0.6.55
